cli:
  app_directory: apps
  base_model: apps.utils.models.BaseModel
  css_framework: tailwind
  module_path: apps
  template_directory: templates
  use_teams: false
default_context:
  _pegasus_version: 2025.11.2
  api_framework: drf
  author_name: Christian Dixon
  bundler: vite
  ci: github_actions
  css_framework: tailwind
  database: postgres
  deploy_platform: heroku_docker
  description: The less boilerplate the better.
  docker_mode: services
  docker_setup: default
  domain_name: 0.0.0.0:8000
  email: cswm7876@yahoo.com
  enable_github_login: y
  enable_google_login: y
  enable_twitter_login: n
  front_end_framework: react
  github_username: codenestcompany
  include_static_files: n
  marketing_email_platform: mailchimp
  plugins:
  - chat
  - ai_images
  post_process: y
  project_name: Python Tutorial
  project_slug: python_tutorial
  python_package_manager: uv
  standalone_front_end: vite
  stripe_payment_mode: checkout
  subscription_billing_model: default
  subscription_pricing_ui: in_app
  type_checker: none
  use_2fa: y
  use_admin_docs: y
  use_ai_rules_agents: y
  use_ai_rules_claude: y
  use_ai_rules_cursor: y
  use_ai_rules_junie: y
  use_api_auth: y
  use_api_keys: y
  use_async: n
  use_auto_reload: y
  use_celery: y
  use_cloud_media_storage: n
  use_dark_mode: y
  use_debug_toolbar: y
  use_ecommerce_example: n
  use_examples: y
  use_flowbite: y
  use_health_checks: y
  use_impersonation: y
  use_sentry: y
  use_shadcn: y
  use_subscriptions: y
  use_teams: n
  use_teams_example: n
  use_translations: y
  use_wagtail: n
  use_watchfiles: y
