/* tslint:disable */
/* eslint-disable */
/**
 * PythonTutorial
 * python tutorial
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AggregateTransactionData
 */
export interface AggregateTransactionData {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AggregateTransactionData
     */
    totalCosts: { [key: string]: any; };
}

/**
 * Check if a given object implements the AggregateTransactionData interface.
 */
export function instanceOfAggregateTransactionData(value: object): boolean {
    if (!('totalCosts' in value)) return false;
    return true;
}

export function AggregateTransactionDataFromJSON(json: any): AggregateTransactionData {
    return AggregateTransactionDataFromJSONTyped(json, false);
}

export function AggregateTransactionDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AggregateTransactionData {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCosts': json['total_costs'],
    };
}

export function AggregateTransactionDataToJSON(value?: AggregateTransactionData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'total_costs': value['totalCosts'],
    };
}

