/* tslint:disable */
/* eslint-disable */
/**
 * PythonTutorial
 * python tutorial
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `INCOME` - Income
 * * `EXPENSE` - Expense
 * @export
 */
export const CategoryTypeEnum = {
    Income: 'INCOME',
    Expense: 'EXPENSE'
} as const;
export type CategoryTypeEnum = typeof CategoryTypeEnum[keyof typeof CategoryTypeEnum];


export function CategoryTypeEnumFromJSON(json: any): CategoryTypeEnum {
    return CategoryTypeEnumFromJSONTyped(json, false);
}

export function CategoryTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryTypeEnum {
    return json as CategoryTypeEnum;
}

export function CategoryTypeEnumToJSON(value?: CategoryTypeEnum | null): any {
    return value as any;
}

