/* tslint:disable */
/* eslint-disable */
/**
 * PythonTutorial
 * python tutorial
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryTypeEnum } from './CategoryTypeEnum';
import {
    CategoryTypeEnumFromJSON,
    CategoryTypeEnumFromJSONTyped,
    CategoryTypeEnumToJSON,
} from './CategoryTypeEnum';

/**
 * 
 * @export
 * @interface Category
 */
export interface Category {
    /**
     * 
     * @type {number}
     * @memberof Category
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Category
     */
    name: string;
    /**
     * 
     * @type {CategoryTypeEnum}
     * @memberof Category
     */
    categoryType: CategoryTypeEnum;
}

/**
 * Check if a given object implements the Category interface.
 */
export function instanceOfCategory(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('name' in value)) return false;
    if (!('categoryType' in value)) return false;
    return true;
}

export function CategoryFromJSON(json: any): Category {
    return CategoryFromJSONTyped(json, false);
}

export function CategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Category {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'categoryType': CategoryTypeEnumFromJSON(json['category_type']),
    };
}

export function CategoryToJSON(value?: Category | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'category_type': CategoryTypeEnumToJSON(value['categoryType']),
    };
}

