/* tslint:disable */
/* eslint-disable */
/**
 * PythonTutorial
 * python tutorial
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Transaction } from './Transaction';
import {
    TransactionFromJSON,
    TransactionFromJSONTyped,
    TransactionToJSON,
} from './Transaction';

/**
 * 
 * @export
 * @interface PaginatedTransactionList
 */
export interface PaginatedTransactionList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedTransactionList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTransactionList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTransactionList
     */
    previous?: string;
    /**
     * 
     * @type {Array<Transaction>}
     * @memberof PaginatedTransactionList
     */
    results?: Array<Transaction>;
}

/**
 * Check if a given object implements the PaginatedTransactionList interface.
 */
export function instanceOfPaginatedTransactionList(value: object): boolean {
    return true;
}

export function PaginatedTransactionListFromJSON(json: any): PaginatedTransactionList {
    return PaginatedTransactionListFromJSONTyped(json, false);
}

export function PaginatedTransactionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedTransactionList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(TransactionFromJSON)),
    };
}

export function PaginatedTransactionListToJSON(value?: PaginatedTransactionList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(TransactionToJSON)),
    };
}

