/* tslint:disable */
/* eslint-disable */
/**
 * PythonTutorial
 * python tutorial
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Category } from './Category';
import {
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
} from './Category';
import type { TransactionTypeEnum } from './TransactionTypeEnum';
import {
    TransactionTypeEnumFromJSON,
    TransactionTypeEnumFromJSONTyped,
    TransactionTypeEnumToJSON,
} from './TransactionTypeEnum';

/**
 * 
 * @export
 * @interface PatchedTransaction
 */
export interface PatchedTransaction {
    /**
     * 
     * @type {number}
     * @memberof PatchedTransaction
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedTransaction
     */
    readonly user?: number;
    /**
     * 
     * @type {Category}
     * @memberof PatchedTransaction
     */
    readonly category?: Category;
    /**
     * 
     * @type {number}
     * @memberof PatchedTransaction
     */
    categoryId?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedTransaction
     */
    amount?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedTransaction
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedTransaction
     */
    description?: string;
    /**
     * 
     * @type {TransactionTypeEnum}
     * @memberof PatchedTransaction
     */
    transactionType?: TransactionTypeEnum;
}

/**
 * Check if a given object implements the PatchedTransaction interface.
 */
export function instanceOfPatchedTransaction(value: object): boolean {
    return true;
}

export function PatchedTransactionFromJSON(json: any): PatchedTransaction {
    return PatchedTransactionFromJSONTyped(json, false);
}

export function PatchedTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedTransaction {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'user': json['user'] == null ? undefined : json['user'],
        'category': json['category'] == null ? undefined : CategoryFromJSON(json['category']),
        'categoryId': json['category_id'] == null ? undefined : json['category_id'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'description': json['description'] == null ? undefined : json['description'],
        'transactionType': json['transaction_type'] == null ? undefined : TransactionTypeEnumFromJSON(json['transaction_type']),
    };
}

export function PatchedTransactionToJSON(value?: PatchedTransaction | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'category_id': value['categoryId'],
        'amount': value['amount'],
        'date': value['date'] == null ? undefined : ((value['date']).toISOString().substring(0,10)),
        'description': value['description'],
        'transaction_type': TransactionTypeEnumToJSON(value['transactionType']),
    };
}

