/* tslint:disable */
/* eslint-disable */
/**
 * PythonTutorial
 * python tutorial
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `INCOME` - Income
 * * `EXPENSE` - Expense
 * @export
 */
export const TransactionTypeEnum = {
    Income: 'INCOME',
    Expense: 'EXPENSE'
} as const;
export type TransactionTypeEnum = typeof TransactionTypeEnum[keyof typeof TransactionTypeEnum];


export function TransactionTypeEnumFromJSON(json: any): TransactionTypeEnum {
    return TransactionTypeEnumFromJSONTyped(json, false);
}

export function TransactionTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionTypeEnum {
    return json as TransactionTypeEnum;
}

export function TransactionTypeEnumToJSON(value?: TransactionTypeEnum | null): any {
    return value as any;
}

