/* tslint:disable */
/* eslint-disable */
/**
 * PythonTutorial
 * python tutorial
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Category } from './Category';
import {
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
} from './Category';
import type { TransactionTypeEnum } from './TransactionTypeEnum';
import {
    TransactionTypeEnumFromJSON,
    TransactionTypeEnumFromJSONTyped,
    TransactionTypeEnumToJSON,
} from './TransactionTypeEnum';

/**
 * 
 * @export
 * @interface Transaction
 */
export interface Transaction {
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    readonly user: number;
    /**
     * 
     * @type {Category}
     * @memberof Transaction
     */
    readonly category: Category;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    categoryId: number;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    amount: string;
    /**
     * 
     * @type {Date}
     * @memberof Transaction
     */
    date: Date;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    description?: string;
    /**
     * 
     * @type {TransactionTypeEnum}
     * @memberof Transaction
     */
    transactionType?: TransactionTypeEnum;
}

/**
 * Check if a given object implements the Transaction interface.
 */
export function instanceOfTransaction(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('user' in value)) return false;
    if (!('category' in value)) return false;
    if (!('categoryId' in value)) return false;
    if (!('amount' in value)) return false;
    if (!('date' in value)) return false;
    return true;
}

export function TransactionFromJSON(json: any): Transaction {
    return TransactionFromJSONTyped(json, false);
}

export function TransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transaction {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'user': json['user'],
        'category': CategoryFromJSON(json['category']),
        'categoryId': json['category_id'],
        'amount': json['amount'],
        'date': (new Date(json['date'])),
        'description': json['description'] == null ? undefined : json['description'],
        'transactionType': json['transaction_type'] == null ? undefined : TransactionTypeEnumFromJSON(json['transaction_type']),
    };
}

export function TransactionToJSON(value?: Transaction | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'category_id': value['categoryId'],
        'amount': value['amount'],
        'date': ((value['date']).toISOString().substring(0,10)),
        'description': value['description'],
        'transaction_type': TransactionTypeEnumToJSON(value['transactionType']),
    };
}

